[package]
name = "linklist"
version = "0.1.0"
authors = ["tyagi <tyagi@piping.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
