[package]
name = "mini-tokio"
version = "0.1.0"
authors = ["tyagig <grvtyagi22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tokio = { version = "1.3", features = ["full"] }
futures = "0.3"
